version: '3'
services:
  db:
    container_name: postgres_base
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PASSWORD_DATABASE}
      POSTGRES_USER: ${USER_DATABASE}
      POSTGRES_DB: ${NAME_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
